# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 481d56af2eb7f6fc77e916aa7685f8b9cedbf65bfef697a2eb2fcbbf588b7839ea921fbfc42f033c7fb1f3442a0177b44d2d827995ccd34619662c50a66bf7f8

test:
  secret_key_base: e76261e1f12a24f4648987e1f57bfb8a68ff24704475ac372702876bc9391477fb0273aa2af770efb142f3a6c7f2d7ebe446bf394444073ba1fa0e7df3214bd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
